path:
  - permissions
plugin: add
actions:
  'administer comments':
    value: 'administer comments'
  'edit own comments':
    value: 'edit own comments'
  'skip comment approval':
    value: 'skip comment approval'

